services:
  stats-server:
    build: stats/stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=100

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=100
      - POSTGRES_USER=admin
      - POSTGRES_DB=stats-db

  main:
    build: main
    container_name: main
    ports:
      - "8080:8080"
    environment:
      - CLIENT_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/main-db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=100

  main-db:
    image: postgres:16.1
    container_name: main-db
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=100
      - POSTGRES_USER=admin
      - POSTGRES_DB=main-db

